# alias vim 'nvim'
# alias vi 'nvim'
# alias ra 'ranger'
# alias ra 'ranger --choosedir=$HOME/.rangerdir;LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias t 'tmux'
alias tn 'tmux new -s zelong'
alias pycharm '/misc/zs7/Zelong/Soft/pycharm-community-2023.1.2/bin/pycharm.sh'
